<?php
    $request = Mage::app()->getRequest();
    $controller = array();
    $controller[] = $request->getRouteName();
    $controller[] = $request->getControllerName();
    $controller[] = $request->getActionName();
    // remove index action or controller
    while (count($controller) > 1) {
        $i = count($controller) - 1;
        if ($controller[$i] != 'index') {
            break;
        }
        array_pop($controller);
    }
    // workaround to determinate highlight type
    if (strtolower($controller[0]) == 'highlight') {
        $controller[] = $request->getParam('type');
    } elseif (strtolower($controller[0]) == 'cms') {
        $pageId = $request->getParam('page_id');
        $urlKey = trim($request->getPathInfo(), '/');
        $controller[] = $urlKey ? $urlKey : 'home';
    }
    $controller = array_map('ucfirst', $controller);

    $config = Mage::getStoreConfig('tm_googleanalytics/events_listen');
    // print_r($config); die;
    // die(json_encode(Mage::getStoreConfig('tm_googleanalytics/events_listen')));

?>
<script type="text/javascript">
    $j(function() {
        analytics.init(
            '<?php echo implode($controller, ' ')?>',
            <?php echo json_encode(Mage::getStoreConfig('tm_googleanalytics/events_listen'))?>
        );
    });
</script>
